[package]
name = "lobby_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
linera-sdk = { version = "0.15.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"





